/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-11-10 at 00:50:56 UTC 
 * Modify at your own risk.
 */

package com.inzynierkanew.entities.players.playerendpoint;

/**
 * Service definition for Playerendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PlayerendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Playerendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the playerendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "playerendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Playerendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Playerendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "authenticatePlayer".
   *
   * This request holds the parameters needed by the playerendpoint server.  After setting any
   * optional parameters, call the {@link AuthenticatePlayer#execute()} method to invoke the remote
   * operation.
   *
   * @param name
   * @param password
   * @return the request
   */
  public AuthenticatePlayer authenticatePlayer(java.lang.String name, java.lang.String password) throws java.io.IOException {
    AuthenticatePlayer result = new AuthenticatePlayer(name, password);
    initialize(result);
    return result;
  }

  public class AuthenticatePlayer extends PlayerendpointRequest<com.inzynierkanew.entities.players.playerendpoint.model.LoginResponse> {

    private static final String REST_PATH = "authenticatePlayer/{name}/{password}";

    /**
     * Create a request for the method "authenticatePlayer".
     *
     * This request holds the parameters needed by the the playerendpoint server.  After setting any
     * optional parameters, call the {@link AuthenticatePlayer#execute()} method to invoke the remote
     * operation. <p> {@link AuthenticatePlayer#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param name
     * @param password
     * @since 1.13
     */
    protected AuthenticatePlayer(java.lang.String name, java.lang.String password) {
      super(Playerendpoint.this, "POST", REST_PATH, null, com.inzynierkanew.entities.players.playerendpoint.model.LoginResponse.class);
      this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
      this.password = com.google.api.client.util.Preconditions.checkNotNull(password, "Required parameter password must be specified.");
    }

    @Override
    public AuthenticatePlayer setAlt(java.lang.String alt) {
      return (AuthenticatePlayer) super.setAlt(alt);
    }

    @Override
    public AuthenticatePlayer setFields(java.lang.String fields) {
      return (AuthenticatePlayer) super.setFields(fields);
    }

    @Override
    public AuthenticatePlayer setKey(java.lang.String key) {
      return (AuthenticatePlayer) super.setKey(key);
    }

    @Override
    public AuthenticatePlayer setOauthToken(java.lang.String oauthToken) {
      return (AuthenticatePlayer) super.setOauthToken(oauthToken);
    }

    @Override
    public AuthenticatePlayer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AuthenticatePlayer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AuthenticatePlayer setQuotaUser(java.lang.String quotaUser) {
      return (AuthenticatePlayer) super.setQuotaUser(quotaUser);
    }

    @Override
    public AuthenticatePlayer setUserIp(java.lang.String userIp) {
      return (AuthenticatePlayer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String name;

    /**

     */
    public java.lang.String getName() {
      return name;
    }

    public AuthenticatePlayer setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String password;

    /**

     */
    public java.lang.String getPassword() {
      return password;
    }

    public AuthenticatePlayer setPassword(java.lang.String password) {
      this.password = password;
      return this;
    }

    @Override
    public AuthenticatePlayer set(String parameterName, Object value) {
      return (AuthenticatePlayer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "findPlayerBySessionId".
   *
   * This request holds the parameters needed by the playerendpoint server.  After setting any
   * optional parameters, call the {@link FindPlayerBySessionId#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public FindPlayerBySessionId findPlayerBySessionId(java.lang.String id) throws java.io.IOException {
    FindPlayerBySessionId result = new FindPlayerBySessionId(id);
    initialize(result);
    return result;
  }

  public class FindPlayerBySessionId extends PlayerendpointRequest<com.inzynierkanew.entities.players.playerendpoint.model.Player> {

    private static final String REST_PATH = "findPlayerBySessionId/{id}";

    /**
     * Create a request for the method "findPlayerBySessionId".
     *
     * This request holds the parameters needed by the the playerendpoint server.  After setting any
     * optional parameters, call the {@link FindPlayerBySessionId#execute()} method to invoke the
     * remote operation. <p> {@link FindPlayerBySessionId#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected FindPlayerBySessionId(java.lang.String id) {
      super(Playerendpoint.this, "POST", REST_PATH, null, com.inzynierkanew.entities.players.playerendpoint.model.Player.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public FindPlayerBySessionId setAlt(java.lang.String alt) {
      return (FindPlayerBySessionId) super.setAlt(alt);
    }

    @Override
    public FindPlayerBySessionId setFields(java.lang.String fields) {
      return (FindPlayerBySessionId) super.setFields(fields);
    }

    @Override
    public FindPlayerBySessionId setKey(java.lang.String key) {
      return (FindPlayerBySessionId) super.setKey(key);
    }

    @Override
    public FindPlayerBySessionId setOauthToken(java.lang.String oauthToken) {
      return (FindPlayerBySessionId) super.setOauthToken(oauthToken);
    }

    @Override
    public FindPlayerBySessionId setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (FindPlayerBySessionId) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public FindPlayerBySessionId setQuotaUser(java.lang.String quotaUser) {
      return (FindPlayerBySessionId) super.setQuotaUser(quotaUser);
    }

    @Override
    public FindPlayerBySessionId setUserIp(java.lang.String userIp) {
      return (FindPlayerBySessionId) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public FindPlayerBySessionId setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public FindPlayerBySessionId set(String parameterName, Object value) {
      return (FindPlayerBySessionId) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPlayer".
   *
   * This request holds the parameters needed by the playerendpoint server.  After setting any
   * optional parameters, call the {@link GetPlayer#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPlayer getPlayer(java.lang.Long id) throws java.io.IOException {
    GetPlayer result = new GetPlayer(id);
    initialize(result);
    return result;
  }

  public class GetPlayer extends PlayerendpointRequest<com.inzynierkanew.entities.players.playerendpoint.model.Player> {

    private static final String REST_PATH = "player/{id}";

    /**
     * Create a request for the method "getPlayer".
     *
     * This request holds the parameters needed by the the playerendpoint server.  After setting any
     * optional parameters, call the {@link GetPlayer#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPlayer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPlayer(java.lang.Long id) {
      super(Playerendpoint.this, "GET", REST_PATH, null, com.inzynierkanew.entities.players.playerendpoint.model.Player.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPlayer setAlt(java.lang.String alt) {
      return (GetPlayer) super.setAlt(alt);
    }

    @Override
    public GetPlayer setFields(java.lang.String fields) {
      return (GetPlayer) super.setFields(fields);
    }

    @Override
    public GetPlayer setKey(java.lang.String key) {
      return (GetPlayer) super.setKey(key);
    }

    @Override
    public GetPlayer setOauthToken(java.lang.String oauthToken) {
      return (GetPlayer) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPlayer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPlayer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPlayer setQuotaUser(java.lang.String quotaUser) {
      return (GetPlayer) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPlayer setUserIp(java.lang.String userIp) {
      return (GetPlayer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPlayer setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPlayer set(String parameterName, Object value) {
      return (GetPlayer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPlayer".
   *
   * This request holds the parameters needed by the playerendpoint server.  After setting any
   * optional parameters, call the {@link ListPlayer#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListPlayer listPlayer() throws java.io.IOException {
    ListPlayer result = new ListPlayer();
    initialize(result);
    return result;
  }

  public class ListPlayer extends PlayerendpointRequest<com.inzynierkanew.entities.players.playerendpoint.model.CollectionResponsePlayer> {

    private static final String REST_PATH = "player";

    /**
     * Create a request for the method "listPlayer".
     *
     * This request holds the parameters needed by the the playerendpoint server.  After setting any
     * optional parameters, call the {@link ListPlayer#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListPlayer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPlayer() {
      super(Playerendpoint.this, "GET", REST_PATH, null, com.inzynierkanew.entities.players.playerendpoint.model.CollectionResponsePlayer.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPlayer setAlt(java.lang.String alt) {
      return (ListPlayer) super.setAlt(alt);
    }

    @Override
    public ListPlayer setFields(java.lang.String fields) {
      return (ListPlayer) super.setFields(fields);
    }

    @Override
    public ListPlayer setKey(java.lang.String key) {
      return (ListPlayer) super.setKey(key);
    }

    @Override
    public ListPlayer setOauthToken(java.lang.String oauthToken) {
      return (ListPlayer) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPlayer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPlayer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPlayer setQuotaUser(java.lang.String quotaUser) {
      return (ListPlayer) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPlayer setUserIp(java.lang.String userIp) {
      return (ListPlayer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPlayer setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPlayer setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPlayer set(String parameterName, Object value) {
      return (ListPlayer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "moveHeroToDifferentLand".
   *
   * This request holds the parameters needed by the playerendpoint server.  After setting any
   * optional parameters, call the {@link MoveHeroToDifferentLand#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @param nextLandId
   * @param x
   * @param y
   * @return the request
   */
  public MoveHeroToDifferentLand moveHeroToDifferentLand(java.lang.Long id, java.lang.Long nextLandId, java.lang.Integer x, java.lang.Integer y) throws java.io.IOException {
    MoveHeroToDifferentLand result = new MoveHeroToDifferentLand(id, nextLandId, x, y);
    initialize(result);
    return result;
  }

  public class MoveHeroToDifferentLand extends PlayerendpointRequest<Void> {

    private static final String REST_PATH = "moveHeroToDifferentLand/{id}/{nextLandId}/{x}/{y}";

    /**
     * Create a request for the method "moveHeroToDifferentLand".
     *
     * This request holds the parameters needed by the the playerendpoint server.  After setting any
     * optional parameters, call the {@link MoveHeroToDifferentLand#execute()} method to invoke the
     * remote operation. <p> {@link MoveHeroToDifferentLand#initialize(com.google.api.client.googleapi
     * s.services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @param nextLandId
     * @param x
     * @param y
     * @since 1.13
     */
    protected MoveHeroToDifferentLand(java.lang.Long id, java.lang.Long nextLandId, java.lang.Integer x, java.lang.Integer y) {
      super(Playerendpoint.this, "POST", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.nextLandId = com.google.api.client.util.Preconditions.checkNotNull(nextLandId, "Required parameter nextLandId must be specified.");
      this.x = com.google.api.client.util.Preconditions.checkNotNull(x, "Required parameter x must be specified.");
      this.y = com.google.api.client.util.Preconditions.checkNotNull(y, "Required parameter y must be specified.");
    }

    @Override
    public MoveHeroToDifferentLand setAlt(java.lang.String alt) {
      return (MoveHeroToDifferentLand) super.setAlt(alt);
    }

    @Override
    public MoveHeroToDifferentLand setFields(java.lang.String fields) {
      return (MoveHeroToDifferentLand) super.setFields(fields);
    }

    @Override
    public MoveHeroToDifferentLand setKey(java.lang.String key) {
      return (MoveHeroToDifferentLand) super.setKey(key);
    }

    @Override
    public MoveHeroToDifferentLand setOauthToken(java.lang.String oauthToken) {
      return (MoveHeroToDifferentLand) super.setOauthToken(oauthToken);
    }

    @Override
    public MoveHeroToDifferentLand setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (MoveHeroToDifferentLand) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public MoveHeroToDifferentLand setQuotaUser(java.lang.String quotaUser) {
      return (MoveHeroToDifferentLand) super.setQuotaUser(quotaUser);
    }

    @Override
    public MoveHeroToDifferentLand setUserIp(java.lang.String userIp) {
      return (MoveHeroToDifferentLand) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public MoveHeroToDifferentLand setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long nextLandId;

    /**

     */
    public java.lang.Long getNextLandId() {
      return nextLandId;
    }

    public MoveHeroToDifferentLand setNextLandId(java.lang.Long nextLandId) {
      this.nextLandId = nextLandId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer x;

    /**

     */
    public java.lang.Integer getX() {
      return x;
    }

    public MoveHeroToDifferentLand setX(java.lang.Integer x) {
      this.x = x;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer y;

    /**

     */
    public java.lang.Integer getY() {
      return y;
    }

    public MoveHeroToDifferentLand setY(java.lang.Integer y) {
      this.y = y;
      return this;
    }

    @Override
    public MoveHeroToDifferentLand set(String parameterName, Object value) {
      return (MoveHeroToDifferentLand) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "registerPlayer".
   *
   * This request holds the parameters needed by the playerendpoint server.  After setting any
   * optional parameters, call the {@link RegisterPlayer#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.inzynierkanew.entities.players.playerendpoint.model.Player}
   * @return the request
   */
  public RegisterPlayer registerPlayer(com.inzynierkanew.entities.players.playerendpoint.model.Player content) throws java.io.IOException {
    RegisterPlayer result = new RegisterPlayer(content);
    initialize(result);
    return result;
  }

  public class RegisterPlayer extends PlayerendpointRequest<com.inzynierkanew.entities.players.playerendpoint.model.Player> {

    private static final String REST_PATH = "registerPlayer";

    /**
     * Create a request for the method "registerPlayer".
     *
     * This request holds the parameters needed by the the playerendpoint server.  After setting any
     * optional parameters, call the {@link RegisterPlayer#execute()} method to invoke the remote
     * operation. <p> {@link RegisterPlayer#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.inzynierkanew.entities.players.playerendpoint.model.Player}
     * @since 1.13
     */
    protected RegisterPlayer(com.inzynierkanew.entities.players.playerendpoint.model.Player content) {
      super(Playerendpoint.this, "POST", REST_PATH, content, com.inzynierkanew.entities.players.playerendpoint.model.Player.class);
    }

    @Override
    public RegisterPlayer setAlt(java.lang.String alt) {
      return (RegisterPlayer) super.setAlt(alt);
    }

    @Override
    public RegisterPlayer setFields(java.lang.String fields) {
      return (RegisterPlayer) super.setFields(fields);
    }

    @Override
    public RegisterPlayer setKey(java.lang.String key) {
      return (RegisterPlayer) super.setKey(key);
    }

    @Override
    public RegisterPlayer setOauthToken(java.lang.String oauthToken) {
      return (RegisterPlayer) super.setOauthToken(oauthToken);
    }

    @Override
    public RegisterPlayer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RegisterPlayer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RegisterPlayer setQuotaUser(java.lang.String quotaUser) {
      return (RegisterPlayer) super.setQuotaUser(quotaUser);
    }

    @Override
    public RegisterPlayer setUserIp(java.lang.String userIp) {
      return (RegisterPlayer) super.setUserIp(userIp);
    }

    @Override
    public RegisterPlayer set(String parameterName, Object value) {
      return (RegisterPlayer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePlayer".
   *
   * This request holds the parameters needed by the playerendpoint server.  After setting any
   * optional parameters, call the {@link RemovePlayer#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePlayer removePlayer(java.lang.Long id) throws java.io.IOException {
    RemovePlayer result = new RemovePlayer(id);
    initialize(result);
    return result;
  }

  public class RemovePlayer extends PlayerendpointRequest<Void> {

    private static final String REST_PATH = "player/{id}";

    /**
     * Create a request for the method "removePlayer".
     *
     * This request holds the parameters needed by the the playerendpoint server.  After setting any
     * optional parameters, call the {@link RemovePlayer#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemovePlayer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePlayer(java.lang.Long id) {
      super(Playerendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePlayer setAlt(java.lang.String alt) {
      return (RemovePlayer) super.setAlt(alt);
    }

    @Override
    public RemovePlayer setFields(java.lang.String fields) {
      return (RemovePlayer) super.setFields(fields);
    }

    @Override
    public RemovePlayer setKey(java.lang.String key) {
      return (RemovePlayer) super.setKey(key);
    }

    @Override
    public RemovePlayer setOauthToken(java.lang.String oauthToken) {
      return (RemovePlayer) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePlayer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePlayer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePlayer setQuotaUser(java.lang.String quotaUser) {
      return (RemovePlayer) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePlayer setUserIp(java.lang.String userIp) {
      return (RemovePlayer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePlayer setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePlayer set(String parameterName, Object value) {
      return (RemovePlayer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePlayerByRegistrationId".
   *
   * This request holds the parameters needed by the playerendpoint server.  After setting any
   * optional parameters, call the {@link RemovePlayerByRegistrationId#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @return the request
   */
  public RemovePlayerByRegistrationId removePlayerByRegistrationId(java.lang.String id) throws java.io.IOException {
    RemovePlayerByRegistrationId result = new RemovePlayerByRegistrationId(id);
    initialize(result);
    return result;
  }

  public class RemovePlayerByRegistrationId extends PlayerendpointRequest<Void> {

    private static final String REST_PATH = "playerbyregistrationid/{id}";

    /**
     * Create a request for the method "removePlayerByRegistrationId".
     *
     * This request holds the parameters needed by the the playerendpoint server.  After setting any
     * optional parameters, call the {@link RemovePlayerByRegistrationId#execute()} method to invoke
     * the remote operation. <p> {@link RemovePlayerByRegistrationId#initialize(com.google.api.client.
     * googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePlayerByRegistrationId(java.lang.String id) {
      super(Playerendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePlayerByRegistrationId setAlt(java.lang.String alt) {
      return (RemovePlayerByRegistrationId) super.setAlt(alt);
    }

    @Override
    public RemovePlayerByRegistrationId setFields(java.lang.String fields) {
      return (RemovePlayerByRegistrationId) super.setFields(fields);
    }

    @Override
    public RemovePlayerByRegistrationId setKey(java.lang.String key) {
      return (RemovePlayerByRegistrationId) super.setKey(key);
    }

    @Override
    public RemovePlayerByRegistrationId setOauthToken(java.lang.String oauthToken) {
      return (RemovePlayerByRegistrationId) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePlayerByRegistrationId setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePlayerByRegistrationId) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePlayerByRegistrationId setQuotaUser(java.lang.String quotaUser) {
      return (RemovePlayerByRegistrationId) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePlayerByRegistrationId setUserIp(java.lang.String userIp) {
      return (RemovePlayerByRegistrationId) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemovePlayerByRegistrationId setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePlayerByRegistrationId set(String parameterName, Object value) {
      return (RemovePlayerByRegistrationId) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateHeroPosition".
   *
   * This request holds the parameters needed by the playerendpoint server.  After setting any
   * optional parameters, call the {@link UpdateHeroPosition#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @param x
   * @param y
   * @return the request
   */
  public UpdateHeroPosition updateHeroPosition(java.lang.Long id, java.lang.Integer x, java.lang.Integer y) throws java.io.IOException {
    UpdateHeroPosition result = new UpdateHeroPosition(id, x, y);
    initialize(result);
    return result;
  }

  public class UpdateHeroPosition extends PlayerendpointRequest<Void> {

    private static final String REST_PATH = "void/{id}/{x}/{y}";

    /**
     * Create a request for the method "updateHeroPosition".
     *
     * This request holds the parameters needed by the the playerendpoint server.  After setting any
     * optional parameters, call the {@link UpdateHeroPosition#execute()} method to invoke the remote
     * operation. <p> {@link UpdateHeroPosition#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @param x
     * @param y
     * @since 1.13
     */
    protected UpdateHeroPosition(java.lang.Long id, java.lang.Integer x, java.lang.Integer y) {
      super(Playerendpoint.this, "PUT", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.x = com.google.api.client.util.Preconditions.checkNotNull(x, "Required parameter x must be specified.");
      this.y = com.google.api.client.util.Preconditions.checkNotNull(y, "Required parameter y must be specified.");
    }

    @Override
    public UpdateHeroPosition setAlt(java.lang.String alt) {
      return (UpdateHeroPosition) super.setAlt(alt);
    }

    @Override
    public UpdateHeroPosition setFields(java.lang.String fields) {
      return (UpdateHeroPosition) super.setFields(fields);
    }

    @Override
    public UpdateHeroPosition setKey(java.lang.String key) {
      return (UpdateHeroPosition) super.setKey(key);
    }

    @Override
    public UpdateHeroPosition setOauthToken(java.lang.String oauthToken) {
      return (UpdateHeroPosition) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateHeroPosition setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateHeroPosition) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateHeroPosition setQuotaUser(java.lang.String quotaUser) {
      return (UpdateHeroPosition) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateHeroPosition setUserIp(java.lang.String userIp) {
      return (UpdateHeroPosition) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public UpdateHeroPosition setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer x;

    /**

     */
    public java.lang.Integer getX() {
      return x;
    }

    public UpdateHeroPosition setX(java.lang.Integer x) {
      this.x = x;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer y;

    /**

     */
    public java.lang.Integer getY() {
      return y;
    }

    public UpdateHeroPosition setY(java.lang.Integer y) {
      this.y = y;
      return this;
    }

    @Override
    public UpdateHeroPosition set(String parameterName, Object value) {
      return (UpdateHeroPosition) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePlayer".
   *
   * This request holds the parameters needed by the playerendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePlayer#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.inzynierkanew.entities.players.playerendpoint.model.Player}
   * @return the request
   */
  public UpdatePlayer updatePlayer(com.inzynierkanew.entities.players.playerendpoint.model.Player content) throws java.io.IOException {
    UpdatePlayer result = new UpdatePlayer(content);
    initialize(result);
    return result;
  }

  public class UpdatePlayer extends PlayerendpointRequest<com.inzynierkanew.entities.players.playerendpoint.model.Player> {

    private static final String REST_PATH = "player";

    /**
     * Create a request for the method "updatePlayer".
     *
     * This request holds the parameters needed by the the playerendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePlayer#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdatePlayer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.inzynierkanew.entities.players.playerendpoint.model.Player}
     * @since 1.13
     */
    protected UpdatePlayer(com.inzynierkanew.entities.players.playerendpoint.model.Player content) {
      super(Playerendpoint.this, "PUT", REST_PATH, content, com.inzynierkanew.entities.players.playerendpoint.model.Player.class);
    }

    @Override
    public UpdatePlayer setAlt(java.lang.String alt) {
      return (UpdatePlayer) super.setAlt(alt);
    }

    @Override
    public UpdatePlayer setFields(java.lang.String fields) {
      return (UpdatePlayer) super.setFields(fields);
    }

    @Override
    public UpdatePlayer setKey(java.lang.String key) {
      return (UpdatePlayer) super.setKey(key);
    }

    @Override
    public UpdatePlayer setOauthToken(java.lang.String oauthToken) {
      return (UpdatePlayer) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePlayer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePlayer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePlayer setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePlayer) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePlayer setUserIp(java.lang.String userIp) {
      return (UpdatePlayer) super.setUserIp(userIp);
    }

    @Override
    public UpdatePlayer set(String parameterName, Object value) {
      return (UpdatePlayer) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Playerendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Playerendpoint}. */
    @Override
    public Playerendpoint build() {
      return new Playerendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PlayerendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPlayerendpointRequestInitializer(
        PlayerendpointRequestInitializer playerendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(playerendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
