/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2016-01-08 17:48:37 UTC)
 * on 2016-01-17 at 21:21:47 UTC 
 * Modify at your own risk.
 */

package com.inzynierkanew.worldUpdateEndpoint.model;

/**
 * Model definition for WorldUpdate.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the worldUpdateEndpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class WorldUpdate extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long currentLandId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long heroId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer newX;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer newY;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCurrentLandId() {
    return currentLandId;
  }

  /**
   * @param currentLandId currentLandId or {@code null} for none
   */
  public WorldUpdate setCurrentLandId(java.lang.Long currentLandId) {
    this.currentLandId = currentLandId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getHeroId() {
    return heroId;
  }

  /**
   * @param heroId heroId or {@code null} for none
   */
  public WorldUpdate setHeroId(java.lang.Long heroId) {
    this.heroId = heroId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNewX() {
    return newX;
  }

  /**
   * @param newX newX or {@code null} for none
   */
  public WorldUpdate setNewX(java.lang.Integer newX) {
    this.newX = newX;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNewY() {
    return newY;
  }

  /**
   * @param newY newY or {@code null} for none
   */
  public WorldUpdate setNewY(java.lang.Integer newY) {
    this.newY = newY;
    return this;
  }

  @Override
  public WorldUpdate set(String fieldName, Object value) {
    return (WorldUpdate) super.set(fieldName, value);
  }

  @Override
  public WorldUpdate clone() {
    return (WorldUpdate) super.clone();
  }

}
