/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-12-09 at 02:24:45 UTC 
 * Modify at your own risk.
 */

package com.inzynierkanew.entities.players.heroendpoint.model;

/**
 * Model definition for Hero.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the heroendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Hero extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer agility;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Integer> army;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long currentLandId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Integer> equippedItems;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer experience;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long gold;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer intelligence;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Integer> items;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer level;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer strength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer x;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer y;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getAgility() {
    return agility;
  }

  /**
   * @param agility agility or {@code null} for none
   */
  public Hero setAgility(java.lang.Integer agility) {
    this.agility = agility;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Integer> getArmy() {
    return army;
  }

  /**
   * @param army army or {@code null} for none
   */
  public Hero setArmy(java.util.List<java.lang.Integer> army) {
    this.army = army;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCurrentLandId() {
    return currentLandId;
  }

  /**
   * @param currentLandId currentLandId or {@code null} for none
   */
  public Hero setCurrentLandId(java.lang.Long currentLandId) {
    this.currentLandId = currentLandId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Integer> getEquippedItems() {
    return equippedItems;
  }

  /**
   * @param equippedItems equippedItems or {@code null} for none
   */
  public Hero setEquippedItems(java.util.List<java.lang.Integer> equippedItems) {
    this.equippedItems = equippedItems;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getExperience() {
    return experience;
  }

  /**
   * @param experience experience or {@code null} for none
   */
  public Hero setExperience(java.lang.Integer experience) {
    this.experience = experience;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGold() {
    return gold;
  }

  /**
   * @param gold gold or {@code null} for none
   */
  public Hero setGold(java.lang.Long gold) {
    this.gold = gold;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Hero setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIntelligence() {
    return intelligence;
  }

  /**
   * @param intelligence intelligence or {@code null} for none
   */
  public Hero setIntelligence(java.lang.Integer intelligence) {
    this.intelligence = intelligence;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Integer> getItems() {
    return items;
  }

  /**
   * @param items items or {@code null} for none
   */
  public Hero setItems(java.util.List<java.lang.Integer> items) {
    this.items = items;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLevel() {
    return level;
  }

  /**
   * @param level level or {@code null} for none
   */
  public Hero setLevel(java.lang.Integer level) {
    this.level = level;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getStrength() {
    return strength;
  }

  /**
   * @param strength strength or {@code null} for none
   */
  public Hero setStrength(java.lang.Integer strength) {
    this.strength = strength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getX() {
    return x;
  }

  /**
   * @param x x or {@code null} for none
   */
  public Hero setX(java.lang.Integer x) {
    this.x = x;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getY() {
    return y;
  }

  /**
   * @param y y or {@code null} for none
   */
  public Hero setY(java.lang.Integer y) {
    this.y = y;
    return this;
  }

  @Override
  public Hero set(String fieldName, Object value) {
    return (Hero) super.set(fieldName, value);
  }

  @Override
  public Hero clone() {
    return (Hero) super.clone();
  }

}
