/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-09-29 at 18:35:12 UTC 
 * Modify at your own risk.
 */

package com.inzynierkanew.entities.map.landendpoint;

/**
 * Service definition for Landendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link LandendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Landendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the landendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "landendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Landendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Landendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "findNeighbours".
   *
   * This request holds the parameters needed by the landendpoint server.  After setting any optional
   * parameters, call the {@link FindNeighbours#execute()} method to invoke the remote operation.
   *
   * @param cursor
   * @return the request
   */
  public FindNeighbours findNeighbours(java.lang.Long cursor) throws java.io.IOException {
    FindNeighbours result = new FindNeighbours(cursor);
    initialize(result);
    return result;
  }

  public class FindNeighbours extends LandendpointRequest<com.inzynierkanew.entities.map.landendpoint.model.CollectionResponseLand> {

    private static final String REST_PATH = "findNeighbours/{cursor}";

    /**
     * Create a request for the method "findNeighbours".
     *
     * This request holds the parameters needed by the the landendpoint server.  After setting any
     * optional parameters, call the {@link FindNeighbours#execute()} method to invoke the remote
     * operation. <p> {@link FindNeighbours#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param cursor
     * @since 1.13
     */
    protected FindNeighbours(java.lang.Long cursor) {
      super(Landendpoint.this, "POST", REST_PATH, null, com.inzynierkanew.entities.map.landendpoint.model.CollectionResponseLand.class);
      this.cursor = com.google.api.client.util.Preconditions.checkNotNull(cursor, "Required parameter cursor must be specified.");
    }

    @Override
    public FindNeighbours setAlt(java.lang.String alt) {
      return (FindNeighbours) super.setAlt(alt);
    }

    @Override
    public FindNeighbours setFields(java.lang.String fields) {
      return (FindNeighbours) super.setFields(fields);
    }

    @Override
    public FindNeighbours setKey(java.lang.String key) {
      return (FindNeighbours) super.setKey(key);
    }

    @Override
    public FindNeighbours setOauthToken(java.lang.String oauthToken) {
      return (FindNeighbours) super.setOauthToken(oauthToken);
    }

    @Override
    public FindNeighbours setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (FindNeighbours) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public FindNeighbours setQuotaUser(java.lang.String quotaUser) {
      return (FindNeighbours) super.setQuotaUser(quotaUser);
    }

    @Override
    public FindNeighbours setUserIp(java.lang.String userIp) {
      return (FindNeighbours) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long cursor;

    /**

     */
    public java.lang.Long getCursor() {
      return cursor;
    }

    public FindNeighbours setCursor(java.lang.Long cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public FindNeighbours set(String parameterName, Object value) {
      return (FindNeighbours) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getLand".
   *
   * This request holds the parameters needed by the landendpoint server.  After setting any optional
   * parameters, call the {@link GetLand#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetLand getLand(java.lang.Long id) throws java.io.IOException {
    GetLand result = new GetLand(id);
    initialize(result);
    return result;
  }

  public class GetLand extends LandendpointRequest<com.inzynierkanew.entities.map.landendpoint.model.Land> {

    private static final String REST_PATH = "land/{id}";

    /**
     * Create a request for the method "getLand".
     *
     * This request holds the parameters needed by the the landendpoint server.  After setting any
     * optional parameters, call the {@link GetLand#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetLand#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetLand(java.lang.Long id) {
      super(Landendpoint.this, "GET", REST_PATH, null, com.inzynierkanew.entities.map.landendpoint.model.Land.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetLand setAlt(java.lang.String alt) {
      return (GetLand) super.setAlt(alt);
    }

    @Override
    public GetLand setFields(java.lang.String fields) {
      return (GetLand) super.setFields(fields);
    }

    @Override
    public GetLand setKey(java.lang.String key) {
      return (GetLand) super.setKey(key);
    }

    @Override
    public GetLand setOauthToken(java.lang.String oauthToken) {
      return (GetLand) super.setOauthToken(oauthToken);
    }

    @Override
    public GetLand setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetLand) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetLand setQuotaUser(java.lang.String quotaUser) {
      return (GetLand) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetLand setUserIp(java.lang.String userIp) {
      return (GetLand) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetLand setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetLand set(String parameterName, Object value) {
      return (GetLand) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertLand".
   *
   * This request holds the parameters needed by the landendpoint server.  After setting any optional
   * parameters, call the {@link InsertLand#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.inzynierkanew.entities.map.landendpoint.model.Land}
   * @return the request
   */
  public InsertLand insertLand(com.inzynierkanew.entities.map.landendpoint.model.Land content) throws java.io.IOException {
    InsertLand result = new InsertLand(content);
    initialize(result);
    return result;
  }

  public class InsertLand extends LandendpointRequest<com.inzynierkanew.entities.map.landendpoint.model.Land> {

    private static final String REST_PATH = "land";

    /**
     * Create a request for the method "insertLand".
     *
     * This request holds the parameters needed by the the landendpoint server.  After setting any
     * optional parameters, call the {@link InsertLand#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertLand#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.inzynierkanew.entities.map.landendpoint.model.Land}
     * @since 1.13
     */
    protected InsertLand(com.inzynierkanew.entities.map.landendpoint.model.Land content) {
      super(Landendpoint.this, "POST", REST_PATH, content, com.inzynierkanew.entities.map.landendpoint.model.Land.class);
    }

    @Override
    public InsertLand setAlt(java.lang.String alt) {
      return (InsertLand) super.setAlt(alt);
    }

    @Override
    public InsertLand setFields(java.lang.String fields) {
      return (InsertLand) super.setFields(fields);
    }

    @Override
    public InsertLand setKey(java.lang.String key) {
      return (InsertLand) super.setKey(key);
    }

    @Override
    public InsertLand setOauthToken(java.lang.String oauthToken) {
      return (InsertLand) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertLand setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertLand) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertLand setQuotaUser(java.lang.String quotaUser) {
      return (InsertLand) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertLand setUserIp(java.lang.String userIp) {
      return (InsertLand) super.setUserIp(userIp);
    }

    @Override
    public InsertLand set(String parameterName, Object value) {
      return (InsertLand) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listLand".
   *
   * This request holds the parameters needed by the landendpoint server.  After setting any optional
   * parameters, call the {@link ListLand#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListLand listLand() throws java.io.IOException {
    ListLand result = new ListLand();
    initialize(result);
    return result;
  }

  public class ListLand extends LandendpointRequest<com.inzynierkanew.entities.map.landendpoint.model.CollectionResponseLand> {

    private static final String REST_PATH = "land";

    /**
     * Create a request for the method "listLand".
     *
     * This request holds the parameters needed by the the landendpoint server.  After setting any
     * optional parameters, call the {@link ListLand#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListLand#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListLand() {
      super(Landendpoint.this, "GET", REST_PATH, null, com.inzynierkanew.entities.map.landendpoint.model.CollectionResponseLand.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListLand setAlt(java.lang.String alt) {
      return (ListLand) super.setAlt(alt);
    }

    @Override
    public ListLand setFields(java.lang.String fields) {
      return (ListLand) super.setFields(fields);
    }

    @Override
    public ListLand setKey(java.lang.String key) {
      return (ListLand) super.setKey(key);
    }

    @Override
    public ListLand setOauthToken(java.lang.String oauthToken) {
      return (ListLand) super.setOauthToken(oauthToken);
    }

    @Override
    public ListLand setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListLand) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListLand setQuotaUser(java.lang.String quotaUser) {
      return (ListLand) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListLand setUserIp(java.lang.String userIp) {
      return (ListLand) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListLand setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListLand setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListLand set(String parameterName, Object value) {
      return (ListLand) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeLand".
   *
   * This request holds the parameters needed by the landendpoint server.  After setting any optional
   * parameters, call the {@link RemoveLand#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveLand removeLand(java.lang.Long id) throws java.io.IOException {
    RemoveLand result = new RemoveLand(id);
    initialize(result);
    return result;
  }

  public class RemoveLand extends LandendpointRequest<Void> {

    private static final String REST_PATH = "land/{id}";

    /**
     * Create a request for the method "removeLand".
     *
     * This request holds the parameters needed by the the landendpoint server.  After setting any
     * optional parameters, call the {@link RemoveLand#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveLand#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveLand(java.lang.Long id) {
      super(Landendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveLand setAlt(java.lang.String alt) {
      return (RemoveLand) super.setAlt(alt);
    }

    @Override
    public RemoveLand setFields(java.lang.String fields) {
      return (RemoveLand) super.setFields(fields);
    }

    @Override
    public RemoveLand setKey(java.lang.String key) {
      return (RemoveLand) super.setKey(key);
    }

    @Override
    public RemoveLand setOauthToken(java.lang.String oauthToken) {
      return (RemoveLand) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveLand setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveLand) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveLand setQuotaUser(java.lang.String quotaUser) {
      return (RemoveLand) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveLand setUserIp(java.lang.String userIp) {
      return (RemoveLand) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveLand setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveLand set(String parameterName, Object value) {
      return (RemoveLand) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateLand".
   *
   * This request holds the parameters needed by the landendpoint server.  After setting any optional
   * parameters, call the {@link UpdateLand#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.inzynierkanew.entities.map.landendpoint.model.Land}
   * @return the request
   */
  public UpdateLand updateLand(com.inzynierkanew.entities.map.landendpoint.model.Land content) throws java.io.IOException {
    UpdateLand result = new UpdateLand(content);
    initialize(result);
    return result;
  }

  public class UpdateLand extends LandendpointRequest<com.inzynierkanew.entities.map.landendpoint.model.Land> {

    private static final String REST_PATH = "land";

    /**
     * Create a request for the method "updateLand".
     *
     * This request holds the parameters needed by the the landendpoint server.  After setting any
     * optional parameters, call the {@link UpdateLand#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateLand#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.inzynierkanew.entities.map.landendpoint.model.Land}
     * @since 1.13
     */
    protected UpdateLand(com.inzynierkanew.entities.map.landendpoint.model.Land content) {
      super(Landendpoint.this, "PUT", REST_PATH, content, com.inzynierkanew.entities.map.landendpoint.model.Land.class);
    }

    @Override
    public UpdateLand setAlt(java.lang.String alt) {
      return (UpdateLand) super.setAlt(alt);
    }

    @Override
    public UpdateLand setFields(java.lang.String fields) {
      return (UpdateLand) super.setFields(fields);
    }

    @Override
    public UpdateLand setKey(java.lang.String key) {
      return (UpdateLand) super.setKey(key);
    }

    @Override
    public UpdateLand setOauthToken(java.lang.String oauthToken) {
      return (UpdateLand) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateLand setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateLand) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateLand setQuotaUser(java.lang.String quotaUser) {
      return (UpdateLand) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateLand setUserIp(java.lang.String userIp) {
      return (UpdateLand) super.setUserIp(userIp);
    }

    @Override
    public UpdateLand set(String parameterName, Object value) {
      return (UpdateLand) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Landendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Landendpoint}. */
    @Override
    public Landendpoint build() {
      return new Landendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link LandendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setLandendpointRequestInitializer(
        LandendpointRequestInitializer landendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(landendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
