package com.inzynierkanew.activities;

import android.os.Bundle;

import com.inzynierkanew.game.GameView;
import com.inzynierkanew.utils.Constants;

public class GameActivity extends BaseActivity {
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(new GameView(this, getIntent().getStringExtra(Constants.SESSION_ID)));

	}

//	@Override
//	protected void onNewIntent(Intent intent) {
//		super.onNewIntent(intent);
//
//		/*
//		 * If we are dealing with an intent generated by the GCMIntentService
//		 * class, then display the provided message.
//		 */
//		if (intent.getBooleanExtra("gcmIntentServiceMessage", false)) {
//
//			showDialog(intent.getStringExtra("message"));
//
//			if (!intent.getBooleanExtra("registrationMessage", false)) {
//				/*
//				 * if we didn't get a registration/unregistration message then
//				 * go get the last 5 messages from app-engine
//				 */
//				new QueryMessagesTask(this, messageEndpoint).execute();
//			}
//		}
//	}
//
//	/*
//	 * Need to run this in background so we don't hold up the UI thread, this
//	 * task will ask the App Engine backend for the last 5 messages sent to it
//	 */
//	private class QueryMessagesTask extends AsyncTask<Void, Void, CollectionResponseMessageData> {
//		Exception exceptionThrown = null;
//		MessageEndpoint messageEndpoint;
//
//		public QueryMessagesTask(Activity activity, MessageEndpoint messageEndpoint) {
//			this.messageEndpoint = messageEndpoint;
//		}
//
//		@Override
//		protected CollectionResponseMessageData doInBackground(Void... params) {
//			try {
//				CollectionResponseMessageData messages = messageEndpoint.listMessages().setLimit(5).execute();
//				return messages;
//			} catch (IOException e) {
//				exceptionThrown = e;
//				return null;
//				// Handle exception in PostExecute
//			}
//		}
//
//		protected void onPostExecute(CollectionResponseMessageData messages) {
//			// Check if exception was thrown
//			if (exceptionThrown != null) {
//				Log.e(RegisterActivity.class.getName(), "Exception when listing Messages", exceptionThrown);
//				showDialog("Failed to retrieve the last 5 messages from " + "the endpoint at " + messageEndpoint.getBaseUrl()
//						+ ", check log for details");
//			} else {
//		/*		TextView messageView = (TextView) findViewById(R.id.message);
//				messageView.setText("Last 5 Messages read from " + messageEndpoint.getBaseUrl() + ":\n");
//				for (MessageData message : messages.getItems()) {
//					messageView.append(message.getMessage() + "\n");
//				}*/
//			}
//		}
//	}*/
}
